apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gxc4grjk5-python-gitops
  description: This is GitOps manifest for gxc4grjk5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=gxc4grjk5-python
    backstage.io/kubernetes-id: gxc4grjk5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gxc4grjk5-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gxc4grjk5-python
